update main branch content to m3ww (latest branch)

diff --git a/.config/eww/scripts/applycolor b/.config/eww/scripts/applycolor
--- a/.config/eww/scripts/applycolor
+++ b/.config/eww/scripts/applycolor
@@ -1,33 +1,68 @@
 #!/usr/bin/env bash
-cp -r images/svg/dark/* images/svg/
 
-filelist=$(ls 'images/svg' -p | grep -v /)
-
+cd "$HOME/.config/eww" || exit
+filelist=$(ls 'images/svg/template/' | grep -v /)
+colorscss=$(cat css/_material.scss)
+colornames=$(cat css/_material.scss | cut -d: -f1)
+colorstrings=$(cat css/_material.scss | cut -d: -f2 | cut -d ' ' -f2 | cut -d ";" -f1)
 IFS=$'\n'
-filearr=($(echo "$filelist"))
+filearr=( $filelist ) # Get colors
+colorlist=( $colornames ) # Array of color names
+colorvalues=( $colorstrings ) # Array of color values
 
-c0=$(cat css/_iconcolor.txt | head -1)
-c1=$(cat css/_iconcolor.txt | head -2 | tail -1)
-c2=$(cat css/_iconcolor.txt | head -3 | tail -1)
-c3=$(cat css/_iconcolor.txt | head -2 | tail -1)
-c4=$(cat css/_iconcolor.txt | head -5 | tail -1)
-c5=$(cat css/_iconcolor.txt | head -6 | tail -1)
+apply_svgs() {
+    for i in "${!filearr[@]}"; do # Loop through folders
+        colorvalue=$(echo "$colorscss" | grep "${filearr[$i]}" | awk '{print $2}' | cut -d ";" -f1)
+        for file in images/svg/template/"${filearr[$i]}"/*; do # Loop through files
+            cp "$file" images/svg/
+            sed -i "s/black/$colorvalue/g" images/svg/"${file##*/}"
+        done
+    done
+}
 
-if [[ "$(cat scripts/workdir/__mode_colors.txt | head -1)" == "one" ]]; then
-    c1=$c0
-    c2=$c0
-    c3=$c0
-    c4=$c0
-    c5=$c0
-fi
+apply_gtklock() {
+    # Check if $HOME/.config/eww/scripts/templates/gtklock/style.css exists
+    if [ ! -f "$HOME/.config/eww/scripts/templates/gtklock/style.css" ]; then
+        echo "Template file not found for Gtklock. Skipping that."
+        return
+    fi
+    # Copy template to style.css
+    cp "$HOME/.config/eww/scripts/templates/gtklock/style.css" "$HOME/.config/gtklock/style.css"
+    # Apply colors
+    for i in "${!colorlist[@]}"; do
+        sed -i "s/${colorlist[$i]};/${colorvalues[$i]};/g" "$HOME/.config/gtklock/style.css"
+    done
+}
 
-sed -i "s/white/$c1/gi" "images/svg/beatmappacks.svg"
-sed -i "s/white/$c2/gi" "images/svg/forum.svg"
-sed -i "s/white/$c3/gi" "images/svg/search.svg"
-sed -i "s/white/$c4/gi" "images/svg/settings.svg"
-sed -i "s/white/$c5/gi" "images/svg/tournaments.svg"
+apply_fuzzel() {
+    # Check if $HOME/.config/eww/scripts/templates/fuzzel/fuzzel.ini exists
+    if [ ! -f "$HOME/.config/eww/scripts/templates/fuzzel/fuzzel.ini" ]; then
+        echo "Template file not found for Fuzzel. Skipping that."
+        return
+    fi
+    # Copy template to style.css
+    cp "$HOME/.config/eww/scripts/templates/fuzzel/fuzzel.ini" "$HOME/.config/fuzzel/fuzzel.ini"
+    # Apply colors
+    for i in "${!colorlist[@]}"; do
+        sed -i "s/${colorlist[$i]}ff/${colorvalues[$i]#\#}ff/g" "$HOME/.config/fuzzel/fuzzel.ini" # note: ff because theyre opaque
+    done
+}
 
-for i in "${!filearr[@]}"; do
-    # echo "images/svg/${filearr[$i]}"
-    sed -i "s/white/$1/gi" "images/svg/${filearr[$i]}"
-done
+apply_foot() {
+    # Check if $HOME/.config/eww/scripts/templates/fuzzel/fuzzel.ini exists
+    if [ ! -f "$HOME/.config/eww/scripts/templates/foot/foot.ini" ]; then
+        echo "Template file not found for Foot. Skipping that."
+        return
+    fi
+    # Copy template to style.css
+    cp "$HOME/.config/eww/scripts/templates/foot/foot.ini" "$HOME/.config/foot/foot.ini"
+    # Apply colors
+    for i in "${!colorlist[@]}"; do
+        sed -i "s/=${colorlist[$i]} #/=${colorvalues[$i]#\#}/g" "$HOME/.config/foot/foot.ini" # note: ff because theyre opaque
+    done
+}
+
+apply_svgs
+apply_gtklock
+apply_fuzzel
+apply_foot
