Tweaks for text and names

diff --git a/diagnose b/diagnose
--- a/diagnose
+++ b/diagnose
@@ -2,14 +2,14 @@
 #
 # This script is for quickly generate helpful info
 # It should be as independent as possible and should not source other files unless it has to
-COLOR_RED='\e[31m'
-COLOR_RESET='\e[00m'
+STY_RED='\e[31m'
+STY_RESET='\e[00m'
 
 cd "$(dirname "$0")";export base="$(pwd)"
 output_file=diagnose.result;rm $output_file
 export LANG=C;export LC_ALL=C
 case $(whoami) in
-  root)echo -e "${COLOR_RED}[$0]: This script is NOT to be executed with sudo or as root. Aborting...${COLOR_RESET}";exit 1;;
+  root)echo -e "${STY_RED}[$0]: This script is NOT to be executed with sudo or as root. Aborting...${STY_RESET}";exit 1;;
 esac
 
 
