Update STY_ vars

diff --git a/diagnose b/diagnose
--- a/diagnose
+++ b/diagnose
@@ -8,13 +8,13 @@
 # Pay attention to the version of Qt which quickshell built against.
 
 STY_RED='\e[31m'
-STY_RESET='\e[00m'
+STY_RST='\e[00m'
 
 cd "$(dirname "$0")";export base="$(pwd)"
 output_file=diagnose.result;rm $output_file
 export LANG=C;export LC_ALL=C
 case $(whoami) in
-  root)echo -e "${STY_RED}[$0]: This script is NOT to be executed with sudo or as root. Aborting...${STY_RESET}";exit 1;;
+  root)echo -e "${STY_RED}[$0]: This script is NOT to be executed with sudo or as root. Aborting...${STY_RST}";exit 1;;
 esac
 
 
